/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/
#include "include/cef_app.h"
#include "../JuceLibraryCode/JuceHeader.h"
#ifdef JUCE_WIN32
#include "Windows.h"
#endif

//==============================================================================
class MapleProcessApplication  : public JUCEApplication
{
public:
    //==============================================================================
    MapleProcessApplication() {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
		// Structure for passing command-line arguments.
		// The definition of this structure is platform-specific.
		CefMainArgs main_args(GetModuleHandle(NULL));

		

		// Execute the sub-process logic. This will block until the sub-process should exit.
		CefExecuteProcess(main_args, nullptr,nullptr);
        
        // Add your application's initialisation code here..
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (MapleProcessApplication)
