/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED


#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CefBrowserObject.h"

//==============================================================================
/**
*/
class MapleLoopsAudioProcessorEditor  : public AudioProcessorEditor,ActionListener
{
public:
    MapleLoopsAudioProcessorEditor (MapleLoopsAudioProcessor&);
    ~MapleLoopsAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
        
	
	void actionListenerCallback(const String& message);

private:
	static int instanceCount;
	static CefContextJob *  context_thread;
	ScopedPointer<CefBrowserObject> myBrowser;

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MapleLoopsAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MapleLoopsAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
